### ISSUE TITLE
רעיונות לפרוייקטים בבסיסי נתונים

### ISSUE THREAD

**Issue by yair-go** [yair-go/150225-5779-Databases#1]

**Comment by itaim18** [comment]
אם יש בעיה (ולו רק אחת בארץ) ניהול מסילות הרכבת.
הפרויקט ימדל ארבעה תחומים:
תחנות
מסלולים
רכבות(הכול עם id’s שמות וכו׳)
ולוחות זמנים
עם זמן כניסה זמן יציאה ותז לא ייחודי לסדר התחנות עבור כל קו

**Comment by yair-go** [comment]
רעיון נחמד, צריך להרחיב קצת
אמורים להיות בסביבות 15 ישויות

**Comment by nit-go** [comment]
אולי אפשר קצת להעזר במציאות
https://www.rail.co.il/about/pages/structure.aspx

**Comment by alonsh194** [comment]
יש לנו רעיון על קניות באינטרנט:
מוכר\ספק
קונים
אתר
מוצר
עגלת קניות
מה אתה אומר המרצה?

**Comment by yair-go** [comment]
קודם כל תכתוב את זה בשרשור של השנה 
[רעיונות לפרוייקטים](https://github.com/Lev-Academic-Center/150225-5780-Databases/issues/1
)

צריך לפתח את זה לפחות ל15 ישויות

**Comment by alonsh194** [comment]
המרצה אתה יכול לעזור לנו בהוספת ישויות?

**Comment by alonsh194** [comment]
אני הבן הזוג שלי ועוד 2 זוגות מהקבוצה שלנו העלנו ביחד את הרעיון של אתר קניות באינטרנט
אלא היישויות:
מוכר 
קונה 
אתר
מוצר
עגלת קניות
חשבון באתר עם סיסמא 
הזדהות ללא סיסמא(מעכב אחר מישלוח) 
היסטוריית קנייה
NewsLetters
דרכי תשלום באשראי
דרך תשלום מזומן
רשימת משאלות 
מתעניין בקניה 
דעת הלקוחות 
פירוט של המוצר /חברה שיוצרת את המוצר

**Comment by nit-go** [comment]
נא להסיר אותי מהכיתוב למייל
תודה

**Comment by yair-go** [comment]
or unsubscribe

**Comment by alonsh194** [comment]
נראלי שעשיתי את זה...אבל מה לגבי מה שעשינו?
זה טוב?
